### ISSUE TITLE
Layout rearrange

### ISSUE THREAD

**Issue by esokullu** [phonetworks/gapp-build#6]
- [ ] Logo on top to the left. (not center)
- [ ] Right in the x position where the content area begins, a text box (input type="text") that lets you define the graph title, so that the file can be saved properly.
- [ ] Right next to the text box, a refresh button to reload the gapp builder from scratch. Make sure to have the user confirm.

**Comment by ozanilbey** [comment]
![graphjs-new-concept](https://user-images.githubusercontent.com/3929181/40889584-c123107a-6771-11e8-8bb4-3bc7f51c01f6.png)

Is this what you want?
